# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Project.create(title: 'Peerigon App Design', description: 'This app helps people organize get-togethers and finding answers to the usual questions: who, what, when, where? The web and mobile app offers various tools for precise coordination and communication. I redesigned the user experience and added 12 usecase illustrations.', customer: 'Peerigon', url:'app_design', preview_image: 'works/apps/App_JudithUrban_01.jpg')
Project.create(title: 'Brimatech Branding', description: 'Brimatech is a Vienna-based consulting company specializing in technology markets. Together with their customers, they develop business models and strategic concepts. As the company brings together markets and technologies, the idea for the new coporate design was based on a simplified bridge emblem. Creative Direction: Armin Bonelli, Qarante/Factor Design', customer: 'Brimatech', url:'brima_branding', preview_image: 'works/brimatech/Brima_01.jpg')
Project.create(title: 'The Book', description: 'SENTIDO is one of the main Thomas Cook Hotels and Resorts brands. The word is Spanish for sense: a sense for hospitality, for the details and for the culinary. I was responsible for the design of this guide which comes in three sizes: an oversize format for display in the hotel lobby, a reading book for the guest rooms and a magazine. Creative direction: Stephan Beisser, Büroecco', customer: 'Thomas Cook Hotels and Resorts', url:'guide_thebook', preview_image: 'works/thebook/TheBook2017_09.jpg')
Project.create(title: 'Award Winning Bird Illustrations', description: 'Last year\'s nicest customers deserved a charming Christmas mailing: We printed my 7 illustrations of native wild birds on groundwood pulp postcards, bound them in a bird-friendly manner and to top it off, we included a simple oak bird feeder and a first tasty treat for our feathered friends. A bit of self-promotion that was well worth the effort, as it received the bronze award in the branding communication category of the 2018 Deutscher Designer Club DDC competition.', customer: 'Büroecco', url:'i_like_birds', preview_image: 'works/birds/Bird_Illustration_JudithUrban_06.jpg')
Project.create(title: 'Website for Quality Bird Food', description: 'Our customer\'s quality bird food is formulated using only the finest natural ingredients. The new website shows it\'s the perfect choice for keeping our garden visitors healthy and happy. Creative direction: Roman Schellmoser, Büroecco', customer: 'Welzhofer', url:'bird_food_website', preview_image: 'works/welzweb/Welz_Web_JudithUrban_01.jpg')
Project.create(title: 'Have You Seen Bigfoot Lately?', description: 'These designs were suggestions for a Swiss manufactorer of cough Drops. To me, Ice bears and Bigfoot seemed like good mascots for the cause.', url:'bigfoot', preview_image: 'works/bigfoot/Winter-Yeti_JudithUrban_05.jpg')
Project.create(title: 'Farmer\'s Market', description: 'Organic food is one of the components of a healthy lifestyle. This market delivers freshest eco friendly household products and speciality groceries directly to their customers\' doorsteps. Büroecco\'s design was just short of tasty vegetable illustrations. Creative direction: Roman Schellmoser, Büroecco', customer: 'Hutzlhof', url:'farmers_market', preview_image: 'works/farmersmarket/Vegetables_JudithUrban_03.jpg')
Project.create(title: 'Illustrated Maps', description: 'This magazine\'s maps were meant tickle a bit of wanderlust. To portray the overall feel of the place, I made detailed sketches of landmarks, hot spots and icons, and added loosely drawn out map outlines in ink. Published in the 2018 version of the SENTIDO book by Thomas Cook Hotels and Resorts.', customer: 'Sentido', url:'maps_vignettes', preview_image: 'works/vignettes/TheBook2018_02.jpg')
Project.create(title: 'Chirpy Advertising Character', description: 'The customer\'s quality bird food is formulated using only the finest natural ingredients. I designed their new brand ambassador called Welzi. Together with the author Isabel Adrianowytsch, I illustrated a small childrens\'s book with the new mascot as main character. Texts: Isbel Adrianowytsch', customer: 'Welzhofer', url:'bird_mascot', preview_image: 'works/welzi/Welz_Maskottchen_JudithUrban_11.jpg')
Project.create(title: 'Web Design for Peerigon', description: 'Whether for Android, iOS, Windows or your fridge, Peerigon develops applications with JavaScript and Node.js which work on a wide variety of platforms. I was responsible for the corporate design, the web concept and web design.', customer: 'Peerigon', url:'peerigon_webdesign', preview_image: 'works/peerigon/Peerigon_CD_JudithUrban_01.jpg')
Project.create(title: 'Production-Ready Ecommerce App', description:'I used the curriculum at Career Foundry to complete a dynamic responsive website and a production-ready consumer web application using Ruby on Rails. My mushroom-hunting app contains functions such as signing up & in, product ratings & reviews, and roles for different users who are able to securely receive credit card payments. During the course, I took a deep dive into frontend development with HTML, CSS, JavaScript, got to know routing based on MVC principles with authentication, and learned how make server requests through AJAX, Angular, and the JSON API.', url:'ecommerce_app', preview_image: 'works/mushrooms/huntingmushrooms02.jpg', link:'www.mushrooming.herokuapp.com' )

Image.create(title:"App Design", url:"works/apps/App_JudithUrban_01.jpg", project_id: 1, css_class: "img-ls")
Image.create(title:"Illustration: Usecase for the Zefix app", url:"works/apps/App_JudithUrban_02.jpg", project_id: 1,css_class: "img-ls")
Image.create(title:"Designing the single screens", url:"works/apps/App_JudithUrban_03.jpg", project_id: 1, css_class: "img-ls")
Image.create(title:"Usecases", url:"works/apps/App_JudithUrban_04.jpg", project_id: 1, css_class: "img-ls")
Image.create(title:"The app in use", url:"works/apps/App_JudithUrban_05.jpg", project_id: 1, css_class: "img-ls")
Image.create(title:"Pocket guide for the logo presentation", url:"works/brimatech/Brima_01.jpg", project_id: 2, css_class: "img-ls")
Image.create(title:"Bridging markets and technology as origami", url:"works/brimatech/Brima_02.jpg", project_id: 2, css_class: "img-ls")
Image.create(title:"Designing the branding elements", url:"works/brimatech/Brima_03.jpg", project_id: 2, css_class: "img-pt")
Image.create(title:"Folder design", url:"works/brimatech/Brima_04.jpg", project_id: 2, css_class: "img-pt")
Image.create(title:"Webdesign", url:"works/brimatech/Brima_05.jpg", project_id: 2, css_class: "img-ls")
Image.create(title:"The oversize book, the reading version and the magazine", url:"works/thebook/TheBook2017_01.jpg", project_id: 3, css_class: "img-ls")
Image.create(title:"Spread page of the book", url:"works/thebook/TheBook2017_02.jpg", project_id: 3, css_class: "img-ls")
Image.create(title:"Page detail", url:"works/thebook/TheBook2017_03.jpg", project_id: 3, css_class: "img-pt")
Image.create(title:"Cover detail", url:"works/thebook/TheBook2017_04.jpg", project_id: 3, css_class: "img-pt")
Image.create(title:"A sense for... the culinary!", url:"works/thebook/TheBook2017_05.jpg", project_id: 3, css_class: "img-ls")
Image.create(title:"Cover of the corresponding magazine", url:"works/thebook/TheBook2017_06.jpg", project_id: 3, css_class: "img-pt")
Image.create(title:"Eye catchers: these hand-drawn illustrations", url:"works/thebook/TheBook2017_07.jpg", project_id: 3, css_class: "img-pt")
Image.create(title:"First page of the travel tips special", url:"works/thebook/TheBook2017_08.jpg", project_id: 3, css_class: "img-pt")
Image.create(title:"That\'s the size of the oversize book", url:"works/thebook/TheBook2017_09.jpg", project_id: 3, css_class: "img-pt")
Image.create(title:"Page detail", url:"works/thebook/TheBook2017_10.jpg", project_id: 3,css_class: "img-ls")
Image.create(title:"The goldfinch", url:"works/birds/Bird_Illustration_JudithUrban_01.jpg", project_id: 4, css_class: "img-ls")
Image.create(title:"For the Christmas mailing, we bound the postcards in a bird-friendly manner", url:"works/birds/Bird_Illustration_JudithUrban_02.jpg", project_id: 4, css_class: "img-ls")
Image.create(title:"My favourite bird illustration: The robin", url:"works/birds/Bird_Illustration_JudithUrban_03.jpg", project_id: 4, css_class: "img-pt")
Image.create(title:"Branding tasty bird treats", url:"works/birds/Bird_Illustration_JudithUrban_04.jpg", project_id: 4, css_class: "img-pt")
Image.create(title:"The birds are sitting on the ribbon", url:"works/birds/Bird_Illustration_JudithUrban_05.jpg", project_id: 4, css_class: "img-ls")
Image.create(title:"The nuthatch", url:"works/birds/Bird_Illustration_JudithUrban_06.jpg", project_id: 4, css_class: "img-pt")
Image.create(title:"Putting it all together", url:"works/birds/Bird_Illustration_JudithUrban_07.jpg", project_id: 4, css_class: "img-pt")
Image.create(title:"Put a lid on it", url:"works/birds/Bird_Illustration_JudithUrban_08.jpg", project_id: 4, css_class: "img-pt")
Image.create(title:"Wren wren wren", url:"works/birds/Bird_Illustration_JudithUrban_09.jpg", project_id: 4, css_class: "img-pt")
Image.create(title:"The bird postcards...", url:"works/birds/Bird_Illustration_JudithUrban_10.jpg", project_id: 4, css_class: "img-ls")
Image.create(title:"Website design", url:"works/welzweb/Welz_Web_JudithUrban_01.jpg", project_id: 5, css_class: "img-ls")
Image.create(title:"Mobile view", url:"works/welzweb/Welz_Web_JudithUrban_02.jpg", project_id: 5, css_class: "img-ls")
Image.create(title:"One of my designs for the website mascot", url:"works/welzweb/Welz_Web_JudithUrban_03.jpg", project_id: 5, css_class: "img-pt")
Image.create(title:"Mobile view", url:"works/welzweb/Welz_Web_JudithUrban_04.jpg", project_id: 5, css_class: "img-pt")
Image.create(title:"Sketches for bigfoot", url:'works/bigfoot/Winter-Yeti_JudithUrban_01.jpg', project_id: 6, css_class: "img-ls")
Image.create(title:"The final packaging idea with the finished bigfood illustration", url:'works/bigfoot/Winter-Yeti_JudithUrban_02.jpg', project_id: 6, css_class: "img-pt")
Image.create(title:"Bigfoot colouring sketch", url:'works/bigfoot/Winter-Yeti_JudithUrban_03.jpg', project_id: 6, css_class: "img-pt")
Image.create(title:"*Nomnomnom*", url:'works/bigfoot/Winter-Yeti_JudithUrban_04.jpg', project_id: 6, css_class: "img-ls")
Image.create(title:"My ice bear design on the rendered cough drop package", url:'works/bigfoot/Winter-Yeti_JudithUrban_05.jpg', project_id: 6, css_class: "img-pt")
Image.create(title:"More bigfoot sketches", url:'works/bigfoot/Winter-Yeti_JudithUrban_06.jpg', project_id: 6, css_class: "img-pt")
Image.create(title:"Poster design", url:'works/farmersmarket/Vegetables_JudithUrban_01.jpg', project_id: 7, css_class: "img-ls")
Image.create(title:"Idea for promoting Oberpfälzisch \"Broutzeit\"", url:'works/farmersmarket/Vegetables_JudithUrban_11.jpg', project_id: 7, css_class: "img-ls")
Image.create(title:"Eat more pears!", url:'works/farmersmarket/Vegetables_JudithUrban_03.jpg', project_id: 7, css_class: "img-pt")
Image.create(title:"Comparing apples and potatoes in Bavarian can be quite confusing", url:'works/farmersmarket/Vegetables_JudithUrban_04.jpg', project_id: 7, css_class: "img-pt")
Image.create(title:"For the monthly newsletter, we needed another illustration style", url:'works/farmersmarket/Vegetables_JudithUrban_08.jpg', project_id: 7, css_class: "img-pt")
Image.create(title:"Treasure chest", url:'works/farmersmarket/Vegetables_JudithUrban_09.jpg', project_id: 7, css_class: "img-pt")
Image.create(title:"A design sketch for the website with one of the vegetable illustrations", url:'works/farmersmarket/Vegetables_JudithUrban_02.jpg', project_id: 7, css_class: "img-ls")
Image.create(title:"Vegetable illustration", url:'works/farmersmarket/Vegetables_JudithUrban_07.jpg', project_id: 7, css_class: "img-ls")
Image.create(title:"Page spread of the Book 2018", url:'works/vignettes/TheBook2018_01.jpg', project_id: 8, css_class: "img-ls")
Image.create(title:"Some of the illustrations I created for the hotel guide", url:'works/vignettes/TheBook2018_02.jpg', project_id: 8, css_class: "img-ls")
Image.create(title:"Illustrated map", url:'works/vignettes/TheBook2018_03.jpg', project_id: 8, css_class: "img-ls")
Image.create(title:"The magazine cover. Kerstin Kriegbaum was responsible for creation and layout", url:'works/vignettes/TheBook2018_04.jpg', project_id: 8, css_class: "img-ls")
Image.create(title:"map illustrations I created for the hotel guide", url:'works/vignettes/TheBook2018_05.jpg', project_id: 8, css_class: "img-ls")
Image.create(title:"page detail", url:'works/vignettes/TheBook2018_06.jpg', project_id: 8, css_class: "img-ls")
Image.create(title:"Page spread of the children\'s book", url:'works/welzi/Welz_Maskottchen_JudithUrban_01.jpg', project_id: 9, css_class: "img-ls")
Image.create(title:"Cover pages", url:'works/welzi/Welz_Maskottchen_JudithUrban_02.jpg', project_id: 9, css_class: "img-ls")
Image.create(title:"Page spread of the children\'s book", url:'works/welzi/Welz_Maskottchen_JudithUrban_03.jpg', project_id: 9, css_class: "img-ls")
Image.create(title:"A band of crickets: Illustration detail", url:'works/welzi/Welz_Maskottchen_JudithUrban_04.jpg', project_id: 9, css_class: "img-pt")
Image.create(title:"Page detail", url:'works/welzi/Welz_Maskottchen_JudithUrban_05.jpg', project_id: 9, css_class: "img-pt")
Image.create(title:"Welzi\'s home is a tree kitchen: Illustration detail", url:'works/welzi/Welz_Maskottchen_JudithUrban_06.jpg', project_id: 9, css_class: "img-ls")
Image.create(title:"I like birds: Idea sketches for the character design", url:'works/welzi/Welz_Maskottchen_JudithUrban_07.jpg', project_id: 9, css_class: "img-pt")
Image.create(title:"Hello, I\'m Welzi", url:'works/welzi/Welz_Maskottchen_JudithUrban_13.jpg', project_id: 9, css_class: "img-pt")
Image.create(title:"Birds leaving for autumn: Page spread of the children\'s book", url:'works/welzi/Welz_Maskottchen_JudithUrban_09.jpg', project_id: 9, css_class: "img-ls")
Image.create(title:"Screen designs for different devices", url:'works/peerigon/Peerigon_CD_JudithUrban_01.jpg', project_id: 10, css_class: "img-ls")
Image.create(title:"The logo on business cards", url:'works/peerigon/Peerigon_CD_JudithUrban_02.jpg', project_id: 10, css_class: "img-ls")
Image.create(title:"Branding for different marketing materials", url:'works/peerigon/Peerigon_CD_JudithUrban_03.jpg', project_id: 10, css_class: "img-pt")
Image.create(title:"The Peerigon logo on shirts", url:'works/peerigon/Peerigon_CD_JudithUrban_04.jpg', project_id: 10, css_class: "img-pt")
Image.create(title:"Idea sketches for the logo", url:'works/peerigon/Peerigon_CD_JudithUrban_05.jpg', project_id: 10, css_class: "img-ls")
Image.create(title:"On this app, people can buy hand-picked mushrooms directly from granddads specialized on mushroom hunting.", url:'works/mushrooms/huntingmushrooms01.jpg', project_id: 11, css_class: "img-ls")
Image.create(title:"It's optimized for different screen sizes", url:'works/mushrooms/huntingmushrooms02.jpg', project_id: 11, css_class: "img-ls")
Image.create(title:"Sketch for defining the app's model associations", url:'works/mushrooms/huntingmushrooms03.jpg', project_id: 11, css_class: "img-pt")
Image.create(title:"Writing ruby", url:'works/mushrooms/huntingmushrooms04.jpg', project_id: 11, css_class: "img-pt")
Image.create(title:"Screens from the mushroom app", url:'works/mushrooms/huntingmushrooms05.jpg', project_id: 11, css_class: "img-lg")